version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: "postgres:15.0"
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: "dpage/pgadmin4"
    env_file:
      - ./database.dev.env
    ports:
      - "5050:80"

  keycloak:
    container_name: keycloak_container
    image: "quay.io/keycloak/keycloak:19.0.3"
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8180:8080"
      - "8787:8787"
    command: start-dev

  blackshot-website:
    image: blackshot-website-image
    build:
      context: .
      dockerfile: Dockerfile-website
    ports:
      - "80:8080"
    restart: always

  auth-core:
    image: auth-core-image
    build:
      context: .
      dockerfile: Dockerfile-auth-core
    ports:
      - "14000:14000"
    network_mode: host
    restart: always

  lobby-core:
    image: lobby-core-image
    build:
      context: .
      dockerfile: Dockerfile-lobby-core
    ports:
      - "30003:30003"
    network_mode: host
    restart: always